app_rama/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('search.urls', namespace='search')),
    path('profile/', include('dashboard.urls', namespace='dashboard')),
    path('authentication/', include('authentication.urls', namespace='authentication')),
    path('accounts/', include('allauth.urls')),
]

authentication/urls.py
from django.urls import path
from .views import LogIn, SignUp, Recover



app_name = 'authentication'



urlpatterns = [
    path('login/', LogIn.as_view(), name='login'),
    path('signup/', SignUp.as_view(), name='signup'),
    path('recover/', Recover.as_view(), name='recover'),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'



urlpatterns = [
    path('', views.home, name='home')
]

search/urls.py
from django.urls import path
from . import views

app_name = 'search'


urlpatterns = [
    path('', views.home, name='home')
]

authentication/models.py
from django.db import models

# Create your models here.

dashboard/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

#niestandardowy model uzytkownika, umozliwia dodanie dodatkowych pol
class CustomUser(AbstractUser):
    # add additional fields in here

    def __str__(self):
        return self.email

search/models.py
from django.db import models

# Create your models here.

authentication/forms.py
from django import forms
from allauth.account.forms import LoginForm, SignupForm



class SimpleLoginForm(LoginForm):
    def __init__(self, *args, **kwargs):
        super(SimpleLoginForm, self).__init__(*args, **kwargs)
        # change fields
        self.fields['login'].widget = forms.TextInput(attrs={'type': 'email',
                                                             'placeholder': 'name@example.com',
                                                             'class': 'form-control'})
        self.fields['password'].widget = forms.PasswordInput(attrs={'type': 'password',
                                                                    'placeholder': '*************',
                                                                    'class': 'form-control'})
        # change label
        self.fields['login'].label = ''
        self.fields['password'].label = ''



class SimpleSignupForm(SignupForm):
    def __init__(self, *args, **kwargs):
        super(SimpleSignupForm, self).__init__(*args, **kwargs)
        #change fields
        self.fields['email'].widget = forms.TextInput(attrs={'type': 'email',
                                                             'placeholder': 'name@example.com',
                                                             'class': 'form-control'})
        self.fields['password1'].widget = forms.PasswordInput(attrs={'type': 'password',
                                                                     'placeholder': '*************',
                                                                     'class': 'form-control'})
        #change labels
        self.fields['email'].label = ''
        # self.fields['email2'].label = ''
        self.fields['password1'].label = ''

search/forms.py
from django import forms
from django.forms import Textarea



class NewJobForm(forms.Form):
    company = forms.CharField(label='Company name')
    website = forms.CharField(label='Website url')
    employ_numbers = forms.CharField(label='Number of employees')
    contract_type = forms.CharField(label='Contract Type')
    salary_st = forms.CharField(label='Salary from')
    salary_end = forms.CharField(label='Salary to')
    title = forms.CharField(label='Job offer title')
    experience_st = forms.CharField(label='Years of experience')
    experience_end = forms.CharField(label='Years of experience')
    description = forms.CharField(label='Job offer description', widget=forms.Textarea())
    location_city = forms.CharField(label='City')
    location_street = forms.CharField(label='Street')

    job_apply = forms.CharField(label='How to apply for a job')
    price = forms.IntegerField(label='Cena pojazdu')
    email = forms.CharField(label='Miasto')

authentication/views.py
from django.shortcuts import render
from allauth.account.views import LoginView, SignupView, PasswordResetView



class LogIn(LoginView):
    template_name = 'authentication/login.html'



class SignUp(SignupView):
    template_name = 'authentication/register.html'



class Recover(PasswordResetView):
    template_name = 'authentication/recover.html'

dashboard/views.py
from django.shortcuts import render



def home(request):
    navbar = 1 #left menu option

    context = {'navbar': navbar}
    return render(request, 'dashboard/home.html', context)

search/views.py
from django.shortcuts import render
from .forms import NewJobForm


def home(request):
    form = NewJobForm()

    context = {'form': form}
    return render(request, 'search/home.html', context)

authentication/templates/authentication/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="LogIn">
  <meta name="author" content="">
  <title>LogIn</title>
  <!-- Favicon -->
  <link rel="icon" href="{% static 'assets/img/brand/favicon.png' %}" type="image/png">
  <!-- Font Awesome 5 -->
  <link rel="stylesheet" href="{% static 'assets/libs/@fortawesome/fontawesome-free/css/all.min.css' %}"><!-- Purpose CSS -->
  <link rel="stylesheet" href="{% static 'assets/css/purpose.css' %}" id="stylesheet">
</head>

<body>
  <div class="main-content">
    <section class="min-vh-100 d-flex align-items-center">
      <div class="bg-img-holder top-0 right-0 col-lg-6 col-xl-8 zindex-100 d-none d-lg-block" data-bg-size="cover" data-bg-position="center">
        <img alt="Image placeholder" src="{% static 'assets/img/backgrounds/img-13.jpg' %}">
      </div>
      <div class="container-fluid">
        <div class="row align-items-center">
          <div class="col-sm-7 col-lg-6 col-xl-4 mx-auto ml-lg-0">
            <div class="px-4 px-lg-6">
              <div>
                <div class="mb-5 text-center">
                  <h6 class="h3">Login</h6>
                  <p class="text-muted mb-0">Sign in to your account to continue.</p>
                  {% for key, value in form.errors.items %}
                  <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {% if key != '__all__' %}{{ key }} {% endif %}{{ value }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  {% endfor %} 
                </div>
                <span class="clearfix"></span>
                <form role="form" method="POST">
                {% csrf_token %}
                  <div class="form-group">
                    <label class="form-control-label">Email address</label>
                    <div class="input-group input-group-merge">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-user"></i></span>
                      </div>
                      {{ form.login }}
                    </div>
                  </div>
                  <div class="form-group mb-4">
                    <div class="d-flex align-items-center justify-content-between">
                      <div>
                        <label class="form-control-label">Password</label>
                      </div>
                      <div class="mb-2">
                        <a href="{% url 'authentication:recover' %}" class="small text-muted text-underline--dashed border-primary">Lost password?</a>
                      </div>
                    </div>
                    <div class="input-group input-group-merge">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-key"></i></span>
                      </div>
                      {{ form.password }}
                    </div>
                  </div>
                  <div class="mt-4">
                    <button type="submit" class="btn btn-block btn-primary">Sign in</button></div>
                </form>
                <div class="mt-4 text-center"><small>Not registered?</small>
                  <a href="{% url 'authentication:signup' %}" class="small font-weight-bold">Create account</a></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  <!-- Core JS - includes jquery, bootstrap, popper, in-view and sticky-kit -->
  <script src="{% static 'assets/js/purpose.core.js' %}"></script>
  <!-- Purpose JS -->
  <script src="{% static 'assets/js/purpose.js' %}"></script>
  <!-- Demo JS - remove it when starting your project -->
  <script src="{% static 'assets/js/demo.js' %}"></script>
</body>

</html>

authentication/templates/authentication/recover.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Recover">
  <meta name="author" content="">
  <title>Recover</title>
  <!-- Favicon -->
  <link rel="icon" href="{% static 'assets/img/brand/favicon.png' %}" type="image/png">
  <!-- Font Awesome 5 -->
  <link rel="stylesheet" href="{% static 'assets/libs/@fortawesome/fontawesome-free/css/all.min.css' %}"><!-- Purpose CSS -->
  <link rel="stylesheet" href="{% static 'assets/css/purpose.css' %}" id="stylesheet">
</head>

<body>
  <div class="main-content">
    <section class="min-vh-100 d-flex align-items-center">
      <div class="bg-img-holder top-0 right-0 col-lg-6 col-xl-8 zindex-100 d-none d-lg-block" data-bg-size="cover" data-bg-position="center">
        <img alt="Image placeholder" src="{% static 'assets/img/backgrounds/img-13.jpg' %}">
      </div>
      <div class="container-fluid">
        <div class="row align-items-center">
          <div class="col-sm-7 col-lg-6 col-xl-4 mx-auto ml-lg-0">
            <div class="px-4 px-lg-6">
              <div>
                <div class="mb-5 text-center">
                  <h6 class="h3">Password reset</h6>
                  <p class="text-muted mb-0">Enter your email below to proceed.</p>
                  {% for key, value in form.errors.items %}
                  <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {% if key != '__all__' %}{{ key }} {% endif %}{{ value }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  {% endfor %} 
                </div>
                <span class="clearfix"></span>
                <form role="form" method="POST">
                {% csrf_token %}
                  <div class="form-group">
                    <div class="input-group input-group-merge">
                      {{ form|crispy }}
                    </div>
                  </div>
                  <div class="mt-4">
                    <button type="submit" class="btn btn-block btn-primary">Reset password</button></div>
                </form>
                <div class="mt-4 text-center"><small>Not registered?</small>
                  <a href="{% url 'authentication:signup' %}" class="small font-weight-bold">Create account</a></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  <!-- Core JS - includes jquery, bootstrap, popper, in-view and sticky-kit -->
  <script src="{% static 'assets/js/purpose.core.js' %}"></script>
  <!-- Purpose JS -->
  <script src="{% static 'assets/js/purpose.js' %}"></script>
  <!-- Demo JS - remove it when starting your project -->
  <script src="{% static 'assets/js/demo.js' %}"></script>
</body>

</html>

authentication/templates/authentication/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Register">
  <meta name="author" content="">
  <title>Register</title>
  <!-- Favicon -->
  <link rel="icon" href="{% static 'assets/img/brand/favicon.png' %}" type="image/png">
  <!-- Font Awesome 5 -->
  <link rel="stylesheet" href="{% static 'assets/libs/@fortawesome/fontawesome-free/css/all.min.css' %}"><!-- Purpose CSS -->
  <link rel="stylesheet" href="{% static 'assets/css/purpose.css' %}" id="stylesheet">
</head>

<body>
  <div class="main-content">
    <section class="min-vh-100 d-flex align-items-center">
      <div class="bg-img-holder top-0 right-0 col-lg-6 col-xl-8 zindex-100 d-none d-lg-block" data-bg-size="cover" data-bg-position="center">
        <img alt="Image placeholder" src="{% static 'assets/img/backgrounds/img-13.jpg' %}">
      </div>
      <div class="container-fluid py-5">
        <div class="row align-items-center">
          <div class="col-sm-7 col-lg-6 col-xl-4 mx-auto ml-lg-0">
            <div class="px-4 px-lg-6">
              <div>
                <div class="mb-5 text-center">
                  <h6 class="h3">Create account</h6>
                  <p class="text-muted mb-0">Made with love by developers for developers.</p>
                  {% for key, value in form.errors.items %}
                  <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {% if key != '__all__' %}{{ key }} {% endif %}{{ value }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  {% endfor %} 
                </div>
                <span class="clearfix"></span>
                <form role="form" method="POST">
                {% csrf_token %}
                  <div class="form-group">
                    <label class="form-control-label">Email address</label>
                    <div class="input-group input-group-merge">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-user"></i></span>
                      </div>
                      {{ form.email }}
                    </div>
                  </div>
                  <div class="form-group mb-4">
                    <label class="form-control-label">Password</label>
                    <div class="input-group input-group-merge">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-key"></i></span>
                      </div>
                      {{ form.password1 }}
                    </div>
                  </div>
                  <div class="my-4">
                    <div class="custom-control custom-checkbox">
                      <input type="checkbox" class="custom-control-input" id="check-privacy">
                      <label class="custom-control-label" for="check-privacy">I agree to the <a href="#">privacy policy</a></label>
                    </div>
                  </div>
                  <div class="mt-4">
                    <button type="submit" class="btn btn-block btn-primary">Create my account</button></div>
                </form>
                <div class="mt-4 text-center"><small>Already have an acocunt?</small>
                  <a href="{% url 'authentication:login' %}" class="small font-weight-bold">Sign in</a></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  <!-- Core JS - includes jquery, bootstrap, popper, in-view and sticky-kit -->
  <script src="{% static 'assets/js/purpose.core.js' %}"></script>
  <!-- Purpose JS -->
  <script src="{% static 'assets/js/purpose.js' %}"></script>
  <!-- Demo JS - remove it when starting your project -->
  <script src="{% static 'assets/js/demo.js' %}"></script>
</body>

</html>

dashboard/templates/dashboard/basic/footer.html
{% load static %}
      <!-- Footer -->
      <div class="footer pt-5 pb-4 footer-light" id="footer-main">
        <div class="row text-center text-sm-left align-items-sm-center">
          <div class="col-sm-6">
            <p class="text-sm mb-0">&copy; 2020 <a href="#" class="h6 text-sm" target="_blank">HireIN.IT</a>. All rights reserved.</p>
          </div>
          <div class="col-sm-6 mb-md-0">
            <ul class="nav justify-content-center justify-content-md-end">
              <li class="nav-item dropdown border-right">
                <a class="nav-link" href="https://tgwebsite.com/" target="_blank">
                   Create - TGwebsite.com
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Terms</a>
              </li>
              <li class="nav-item">
                <a class="nav-link pr-0" href="#">Contact</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
     

dashboard/templates/dashboard/basic/header-left.html
{% load static %}
    <div class="sidenav" id="sidenav-main">
      <!-- Sidenav header -->
      <div class="sidenav-header d-flex align-items-center">
        <a class="navbar-brand" href="#">
          <img src="{% static 'assets/img/brand/logo.png' %}" class="navbar-brand-img" alt="..." style="height: 50px;">
        </a>
        <div class="ml-auto">
          <!-- Sidenav toggler -->
          <div class="sidenav-toggler sidenav-toggler-dark d-md-none" data-action="sidenav-unpin" data-target="#sidenav-main">
            <div class="sidenav-toggler-inner">
              <i class="sidenav-toggler-line bg-white"></i>
              <i class="sidenav-toggler-line bg-white"></i>
              <i class="sidenav-toggler-line bg-white"></i>
            </div>
          </div>
        </div>
      </div>
      <!-- User mini profile -->
      <div class="sidenav-user d-flex flex-column align-items-center justify-content-between text-center">
        <!-- Avatar -->
        <div>
          <a href="#" class="avatar rounded-circle avatar-xl">
            <img alt="Image placeholder" src="{% static 'assets/img/theme/light/1.png' %}" class="">
          </a>
          <div class="mt-4">
            <h5 class="mb-0 text-white">IBM Company</h5>
            <span class="d-block text-sm text-white opacity-8 mb-3">Welcome in you're dashboard</span>
            <a href="#" class="btn btn-sm btn-white btn-icon rounded-pill shadow hover-translate-y-n3">
              <span class="btn-inner--icon"><i class="fas fa-coins"></i></span>
              <span class="btn-inner--text">2.300 GBP</span>
            </a>
          </div>
        </div>
        <!-- User info -->
        <!-- Actions -->
        <div class="w-100 mt-4 actions d-flex justify-content-between">
          <a href="../application/user/profile.html" class="action-item action-item-lg text-white pl-0">
            <i class="far fa-user"></i>
          </a>
          <a href="#modal-chat" class="action-item action-item-lg text-white" data-toggle="modal">
            <i class="far fa-comment-alt"></i>
          </a>
          <a href="../application/shop/invoices.html" class="action-item action-item-lg text-white pr-0">
            <i class="fas fa-paste"></i>
          </a>
        </div>
      </div>
      <!-- Application nav -->
      <div class="nav-application clearfix">
        <a href="#" class="btn btn-square text-sm {% if navbar == 1 %}active{% endif %}">
          <span class="btn-inner--icon d-block"><i class="far fa-plus-square fa-2x"></i></span>
          <span class="btn-inner--icon d-block pt-2">New job</span>
        </a>
        <a href="#" class="btn btn-square text-sm {% if navbar == 2 %}active{% endif %}">
          <span class="btn-inner--icon d-block"><i class="fas fa-th-list fa-2x"></i></span>
          <span class="btn-inner--icon d-block pt-2">Job list</span>
        </a>
      </div>
    </div>

dashboard/templates/dashboard/basic/header.html
{% load static %}
      <nav class="navbar navbar-main navbar-expand-lg navbar-dark bg-primary navbar-border" id="navbar-main">
        <div class="container-fluid">
          <!-- Brand + Toggler (for mobile devices) -->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-main-collapse" aria-controls="navbar-main-collapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <!-- Navbar nav -->
          <div class="collapse navbar-collapse navbar-collapse-fade" id="navbar-main-collapse">
            <ul class="navbar-nav align-items-lg-center">
              <!-- Overview  -->
              <li class="border-top opacity-2 my-2"></li>
              <!-- Home  -->
              <li class="nav-item ">
                <a class="nav-link pl-lg-0" href="#">
                  New Job
                </a>
              </li>
              <li class="border-top opacity-2 my-2"></li>
              <!-- Home  -->
              <li class="nav-item">
                <a class="nav-link" href="#">
                  My jobs
                </a>
              </li>
            </ul><!-- Right menu -->
            <ul class="navbar-nav ml-lg-auto align-items-center d-none d-lg-flex">
              <li class="nav-item">
                <a href="#" class="nav-link nav-link-icon sidenav-toggler" data-action="sidenav-pin" data-target="#sidenav-main"><i class="fas fa-bars"></i></a>
              </li>
              <li class="nav-item">
                <a class="nav-link pr-lg-0" href="#" role="button">
                  <div class="align-items-center">
                    <div class="ml-2 d-none d-lg-block">
                      <button class="btn btn-sm rounded-pill btn-white">Log out</button>
                    </div>
                  </div>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

search/templates/basic/header.html
{% load static %}
  <header class="header header-transparent" id="header-main">
    <!-- Main navbar -->
    <nav class="navbar navbar-main navbar-expand-lg navbar-transparent navbar-dark bg-dark" id="navbar-main">
      <div class="container-fluid px-lg-0">
        <!-- Logo -->
        <a class="navbar-brand mr-lg-5" href="#">
          <div class="d-none d-md-block">
            <img alt="Image placeholder" src="{% static 'assets/img/brand/logo.png' %}" id="navbar-logo" style="height: 65px;">
          </div>
          <div class="d-md-none">
            <img alt="Image placeholder" src="{% static 'assets/img/brand/logo.png' %}" id="navbar-logo" style="height: 65px;">
          </div>
        </a>
        <!-- Navbar collapse trigger -->
        <button class="navbar-toggler pr-0" type="button" data-toggle="collapse" data-target="#navbar-main-collapse" aria-controls="navbar-main-collapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Navbar nav -->
        <div class="collapse navbar-collapse" id="navbar-main-collapse">
          <ul class="navbar-nav align-items-lg-center ml-lg-auto">
            <li class="nav-item">
              <a class="nav-link" href="#"><i class="fab fa-facebook-f"></i></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#"><i class="fab fa-linkedin"></i></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#"><i class="fab fa-instagram"></i></a>
            </li>
            <li class="nav-item mr-0">
              <a href="#" class="nav-link d-lg-none">Post an ad</a>
              <a href="#" class="btn btn-white d-none d-lg-inline-flex" data-toggle="tooltip" data-placement="left" title="Post you're escort">
                Post Job
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>

search/templates/search/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
  <meta name="description" content="HireIn.IT Coming Soon...">
  <meta name="author" content="HireIn.IT">
  <title>HireIn.IT Coming Soon...</title>
  <style>
    @keyframes hidePreloader {
      0% {
        width: 100%;
        height: 100%
      }

      100% {
        width: 0;
        height: 0
      }
    }

    body>div.preloader {
      position: fixed;
      background: #fff;
      width: 100%;
      height: 100%;
      z-index: 1071;
      opacity: 0;
      transition: opacity .5s ease;
      overflow: hidden;
      pointer-events: none;
      display: flex;
      align-items: center;
      justify-content: center
    }

    body:not(.loaded)>div.preloader {
      opacity: 1
    }

    body:not(.loaded) {
      overflow: hidden
    }

    body.loaded>div.preloader {
      animation: hidePreloader .5s linear .5s forwards
    }
  </style>
  <script>
    window.addEventListener("load", function() {
      setTimeout(function() {
        document.querySelector("body").classList.add("loaded")
      }, 300)
    })
  </script>
  <link rel="icon" href="{% static 'assets/img/brand/favicon.png' %}" type="image/png">
  <!-- Font Awesome 5 -->
  <link rel="stylesheet" href="{% static 'assets/libs/@fortawesome/fontawesome-pro/css/all.min.css' %}"><!-- Purpose CSS -->
  <link rel="stylesheet" href="{% static 'assets/css/purpose.css' %}" id="stylesheet">
</head>

<body>
  <div class=preloader>
    <div class="spinner-border text-primary" role=status><span class=sr-only>Loading...</span></div>
  </div>
  <section class="vh-100 d-flex align-items-center bg-gradient-primary">
    <div class="container py-md-8 position-relative zindex-100">
      <div class="col px-0">
        <div class="row justify-content-center">
          <div class="col-lg-7 text-center">
            <h6 class="my-4 text-white font-weight-light text-uppercase ls-2">Coming soon...</h6><img alt="Image placeholder" src="{% static 'assets/img/brand/3.png' %}" class="w-75 mb-5">
            <p class="px-md-5 text-white mb-5">Soon, the best portal with job offers for the IT industry and not only!</p>
            <div class="countdown countdown-hero countdown-hero-dark" data-countdown-date=03/01/2020></div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Core JS - includes jquery, bootstrap, popper, in-view and sticky-kit -->
  <script src="{% static 'assets/js/purpose.core.js' %}"></script>
  <!-- Page JS -->
  <script src="{% static 'assets/libs/jquery-countdown/dist/jquery.countdown.min.js' %}"></script>
  <!-- Purpose JS -->
  <script src="{% static 'assets/js/purpose.js' %}"></script>
</body>

</html>